<?php

namespace Tritility\ExcelToCsv;

use Illuminate\Support\ServiceProvider;

class ExcelToCsvServiceProvider extends ServiceProvider
{
    public function boot(\Illuminate\Routing\Router $router){
        $this->commands([
            ExcelToCsv::class
        ]);
        $this->loadFactoriesFrom(__DIR__ . '/GenerateExcelToCsv.php');
    }

    public function register()
    {
//        parent::register(); // TODO: Change the autogenerated stub
    }
}
